/* exports.js — render the bulk-download grids on /pages/exports/.
 *
 * Reads data/exports/manifest.json and renders one card per file, grouped
 * by format. The manifest is regenerated by build/build-exports.mjs on
 * every build, so the page reflects the current corpus without redeploys.
 */
(function () {
  'use strict';

  var TYPE_LABELS = {
    characters: { cn: '字',     py: 'zì',      en: 'Characters' },
    vocab:      { cn: '词',     py: 'cí',      en: 'Vocabulary' },
    chengyu:    { cn: '成语',   py: 'chéngyǔ', en: 'Chengyu' },
    all:        { cn: '全部',   py: 'quánbù',  en: 'All combined' }
  };

  var FORMAT_LABELS = {
    'pleco':     { cn: 'Pleco',     subtitle: 'tab-separated card files' },
    'anki-tsv':  { cn: 'Anki TSV',  subtitle: 'columns: Hanzi · Pinyin · English · …' },
    'anki-apkg': { cn: 'Anki .apkg', subtitle: 'styled deck packages — double-click to import' }
  };

  function escapeHtml(s) {
    return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  function formatBytes(n) {
    if (n < 1024) return n + ' B';
    if (n < 1024 * 1024) return (n / 1024).toFixed(1) + ' KB';
    return (n / 1024 / 1024).toFixed(2) + ' MB';
  }

  function renderCard(entry, sizeMap) {
    var t = TYPE_LABELS[entry.type] || { cn: entry.type, py: '', en: entry.type };
    var size = sizeMap[entry.file];
    var href = '../../data/exports/' + entry.file;
    return (
      '<a class="export-card" href="' + escapeHtml(href) + '" download data-file="' + escapeHtml(entry.file) + '">' +
        '<div class="export-card-head">' +
          '<span class="export-card-cn" lang="zh">' + escapeHtml(t.cn) + '</span>' +
          (t.py ? '<span class="export-card-py">' + escapeHtml(t.py) + '</span>' : '') +
        '</div>' +
        '<div class="export-card-en">' + escapeHtml(t.en) + '</div>' +
        '<div class="export-card-meta">' +
          '<span class="export-card-count">' + entry.count + ' cards</span>' +
          (size ? '<span class="export-card-size">' + formatBytes(size) + '</span>' : '') +
        '</div>' +
        '<span class="export-card-action">Download →</span>' +
      '</a>'
    );
  }

  function renderGroup(format, items, sizeMap) {
    var grid = document.querySelector('[data-exports-format="' + format + '"]');
    if (!grid) return;
    var label = FORMAT_LABELS[format] || { subtitle: '' };
    var html = '';
    if (label.subtitle) {
      html += '<p class="exports-format-sub">' + escapeHtml(label.subtitle) + '</p>';
    }
    html += '<div class="exports-cards">' +
      items.map(function (i) { return renderCard(i, sizeMap); }).join('') +
      '</div>';
    grid.innerHTML = html;
  }

  // Optional HEAD-request size lookups; if a request fails we just omit the
  // size from the card. Keeps the page useful even if the static server
  // doesn't respond to HEAD.
  function fetchSizes(files) {
    var sizeMap = {};
    return Promise.all(files.map(function (f) {
      return fetch('../../data/exports/' + f, { method: 'HEAD' })
        .then(function (r) {
          var len = r.headers.get('content-length');
          if (len) sizeMap[f] = parseInt(len, 10);
        })
        .catch(function () {});
    })).then(function () { return sizeMap; });
  }

  fetch('../../data/exports/manifest.json')
    .then(function (r) {
      if (!r.ok) throw new Error('manifest not found');
      return r.json();
    })
    .then(function (manifest) {
      var byFormat = {};
      manifest.files.forEach(function (f) {
        if (!byFormat[f.format]) byFormat[f.format] = [];
        byFormat[f.format].push(f);
      });
      return fetchSizes(manifest.files.map(function (f) { return f.file; }))
        .then(function (sizeMap) {
          Object.keys(byFormat).forEach(function (fmt) {
            renderGroup(fmt, byFormat[fmt], sizeMap);
          });
        });
    })
    .catch(function (err) {
      console.warn('exports: failed to load manifest', err);
      document.querySelectorAll('[data-exports-format]').forEach(function (el) {
        el.innerHTML = '<p class="exports-empty">Couldn’t load the export manifest. Try refreshing.</p>';
      });
    });
})();
