/* exports.js — render the bulk-download library on /pages/exports/.
 *
 * Reads data/exports/manifest.json and renders five sections:
 *   1. Featured intent decks (Survival Mandarin, Buddhist Reader, …)
 *   2. HSK ladder (HSK 1, HSK 1-2, …, HSK 1-6)
 *   3. By type (characters / vocab / chengyu / grammar)
 *   4. By tag (semantic chips)
 *   5. Global combined decks (the original 11 files)
 *
 * Manifest is regenerated by build/build-exports.mjs on every build, so
 * the page always reflects the current corpus without a code change.
 */
(function () {
  'use strict';

  // ────────────────────── DOM helpers ──────────────────────

  function escapeHtml(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  function formatBytes(n) {
    if (!n && n !== 0) return '';
    if (n < 1024) return n + ' B';
    if (n < 1024 * 1024) return (n / 1024).toFixed(0) + ' KB';
    return (n / 1024 / 1024).toFixed(2) + ' MB';
  }

  // ────────────────────── HSK breakdown badge ──────────────────────
  // Renders a compact "mostly HSK 3" or "HSK 1-3" hint on each slice card,
  // so a learner glancing at "Buddhist Reader" can see the level demand
  // without opening the deck.
  function hskBadge(breakdown) {
    if (!breakdown) return '';
    var levels = Object.keys(breakdown)
      .filter(function (k) { return k.indexOf('hsk-') === 0; })
      .map(function (k) { return [parseInt(k.slice(4), 10), breakdown[k]]; })
      .filter(function (p) { return Number.isFinite(p[0]); });
    if (levels.length === 0) return '';
    levels.sort(function (a, b) { return a[0] - b[0]; });
    var min = levels[0][0];
    var max = levels[levels.length - 1][0];
    var label = min === max ? ('HSK ' + min) : ('HSK ' + min + '–' + max);
    var unknown = breakdown.unknown || 0;
    if (unknown > 0) {
      var totalKnown = levels.reduce(function (s, p) { return s + p[1]; }, 0);
      if (unknown > totalKnown) return ''; // dominated by unknowns — don't lie
    }
    return '<span class="slice-card-hsk">' + escapeHtml(label) + '</span>';
  }

  // ────────────────────── Slice card ──────────────────────
  // Renders one downloadable slice with two actions (Anki + Pleco) and
  // optional HSK badge / description.
  function renderSliceCard(slice, sizeMap) {
    var apkgHref = '../../data/exports/' + slice.apkg;
    var plecoHref = '../../data/exports/' + slice.pleco;
    var apkgSize = sizeMap[slice.apkg];
    var description = slice.description ? '<p class="slice-card-desc">' + escapeHtml(slice.description) + '</p>' : '';
    var cn = slice.cn ? '<span class="slice-card-cn" lang="zh">' + escapeHtml(slice.cn) + '</span>' : '';
    return (
      '<article class="slice-card" data-dimension="' + escapeHtml(slice.dimension) + '">' +
        '<header class="slice-card-head">' +
          cn +
          '<h3 class="slice-card-title">' + escapeHtml(slice.name) + '</h3>' +
        '</header>' +
        description +
        '<div class="slice-card-meta">' +
          '<span class="slice-card-count">' + slice.count + ' cards</span>' +
          hskBadge(slice.hskBreakdown) +
          (apkgSize ? '<span class="slice-card-size">' + escapeHtml(formatBytes(apkgSize)) + '</span>' : '') +
        '</div>' +
        '<div class="slice-card-actions">' +
          '<a class="slice-card-btn slice-card-btn--pleco" href="' + escapeHtml(plecoHref) + '" download>Pleco .txt</a>' +
          '<a class="slice-card-btn slice-card-btn--anki" href="' + escapeHtml(apkgHref) + '" download>Anki .apkg</a>' +
        '</div>' +
      '</article>'
    );
  }

  // ────────────────────── Section renderers ──────────────────────

  function renderSliceGrid(target, slices, sizeMap, opts) {
    var el = document.querySelector(target);
    if (!el) return;
    if (slices.length === 0) {
      el.innerHTML = '<p class="exports-empty">No slices available — try rebuilding.</p>';
      return;
    }
    var sortKey = opts && opts.sortKey;
    if (sortKey) slices = slices.slice().sort(sortKey);
    el.innerHTML = '<div class="slice-grid">' +
      slices.map(function (s) { return renderSliceCard(s, sizeMap); }).join('') +
      '</div>';
  }

  // ────────────────────── Legacy global decks ──────────────────────
  // The original 11 files (pleco-*.txt, anki-*.tsv, *.apkg) still exist
  // and are useful for "give me the entire corpus" — render them as a
  // simple grid keyed by format like the old UI did.

  var TYPE_LABELS = {
    characters: { cn: '字',     py: 'zì',      en: 'Characters' },
    vocab:      { cn: '词',     py: 'cí',      en: 'Vocabulary' },
    chengyu:    { cn: '成语',   py: 'chéngyǔ', en: 'Chengyu' },
    all:        { cn: '全部',   py: 'quánbù',  en: 'All combined' }
  };

  var FORMAT_LABELS = {
    'pleco':     { subtitle: 'tab-separated card files (open in Pleco)' },
    'anki-tsv':  { subtitle: 'columns: Hanzi · Pinyin · English · … (custom mapping)' },
    'anki-apkg': { subtitle: 'styled deck packages — double-click to import' }
  };

  function renderLegacyCard(entry, sizeMap) {
    var t = TYPE_LABELS[entry.type] || { cn: entry.type, py: '', en: entry.type };
    var size = sizeMap[entry.file];
    var href = '../../data/exports/' + entry.file;
    return (
      '<a class="export-card" href="' + escapeHtml(href) + '" download data-file="' + escapeHtml(entry.file) + '">' +
        '<div class="export-card-head">' +
          '<span class="export-card-cn" lang="zh">' + escapeHtml(t.cn) + '</span>' +
          (t.py ? '<span class="export-card-py">' + escapeHtml(t.py) + '</span>' : '') +
        '</div>' +
        '<div class="export-card-en">' + escapeHtml(t.en) + '</div>' +
        '<div class="export-card-meta">' +
          '<span class="export-card-count">' + entry.count + ' cards</span>' +
          (size ? '<span class="export-card-size">' + formatBytes(size) + '</span>' : '') +
        '</div>' +
        '<span class="export-card-action">Download →</span>' +
      '</a>'
    );
  }

  function renderLegacyGroup(format, items, sizeMap) {
    var grid = document.querySelector('[data-exports-format="' + format + '"]');
    if (!grid) return;
    var label = FORMAT_LABELS[format] || { subtitle: '' };
    var html = '';
    if (label.subtitle) html += '<p class="exports-format-sub">' + escapeHtml(label.subtitle) + '</p>';
    html += '<div class="exports-cards">' +
      items.map(function (i) { return renderLegacyCard(i, sizeMap); }).join('') +
      '</div>';
    grid.innerHTML = html;
  }

  // ────────────────────── Size lookups ──────────────────────
  // HEAD-request best effort. If the server doesn't support HEAD we just
  // omit the size badge — the page is still fully usable.
  function fetchSizes(paths) {
    var sizeMap = {};
    return Promise.all(paths.map(function (p) {
      return fetch('../../data/exports/' + p, { method: 'HEAD' })
        .then(function (r) {
          var len = r.headers.get('content-length');
          if (len) sizeMap[p] = parseInt(len, 10);
        })
        .catch(function () {});
    })).then(function () { return sizeMap; });
  }

  // ────────────────────── Main ──────────────────────

  fetch('../../data/exports/manifest.json')
    .then(function (r) {
      if (!r.ok) throw new Error('manifest not found');
      return r.json();
    })
    .then(function (manifest) {
      var slices = manifest.slices || [];
      var files = manifest.files || [];

      // Group slices by dimension for routing into the page sections.
      var byDim = {};
      slices.forEach(function (s) {
        if (!byDim[s.dimension]) byDim[s.dimension] = [];
        byDim[s.dimension].push(s);
      });

      // HEAD all paths up front so badges render in one paint.
      var allPaths = []
        .concat(slices.map(function (s) { return s.apkg; }))
        .concat(slices.map(function (s) { return s.pleco; }))
        .concat(files.map(function (f) { return f.file; }));

      return fetchSizes(allPaths).then(function (sizeMap) {
        // 1. Intent decks — sort by size descending so the largest/most
        //    immediately useful decks lead.
        renderSliceGrid('[data-slice-section="intent"]', byDim.intent || [], sizeMap, {
          sortKey: function (a, b) { return b.count - a.count; },
        });

        // 2. HSK ladder — natural numeric order.
        renderSliceGrid('[data-slice-section="hsk-ladder"]', byDim['hsk-ladder'] || [], sizeMap, {
          sortKey: function (a, b) { return a.criterion - b.criterion; },
        });

        // 3. By single HSK level — natural numeric order.
        renderSliceGrid('[data-slice-section="hsk"]', byDim.hsk || [], sizeMap, {
          sortKey: function (a, b) { return a.criterion - b.criterion; },
        });

        // 4. By type — natural type order: characters → vocab → chengyu → grammar.
        var typeOrder = { character: 0, vocab: 1, chengyu: 2, grammar: 3 };
        renderSliceGrid('[data-slice-section="type"]', byDim.type || [], sizeMap, {
          sortKey: function (a, b) { return (typeOrder[a.criterion] || 99) - (typeOrder[b.criterion] || 99); },
        });

        // 5. By tag — alpha by name.
        renderSliceGrid('[data-slice-section="tag"]', byDim.tag || [], sizeMap, {
          sortKey: function (a, b) { return a.name.localeCompare(b.name); },
        });

        // 6. Legacy global decks (the original 11) — grouped by format.
        var byFormat = {};
        files.forEach(function (f) {
          if (!byFormat[f.format]) byFormat[f.format] = [];
          byFormat[f.format].push(f);
        });
        Object.keys(byFormat).forEach(function (fmt) {
          renderLegacyGroup(fmt, byFormat[fmt], sizeMap);
        });
      });
    })
    .catch(function (err) {
      console.warn('exports: failed to load manifest', err);
      document.querySelectorAll('[data-slice-section], [data-exports-format]').forEach(function (el) {
        el.innerHTML = '<p class="exports-empty">Couldn’t load the export manifest. Try refreshing.</p>';
      });
    });
})();
